api_platform:
    title: Test API
    version: 0.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        yaml: ['application/x-yaml']
        jsonopenapi: ['application/vnd.openapi+json']
        json:     ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_enabled: false
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
